<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CLOSE' => 'Close',
    'ADD_NODE' => 'Add node',
    'ADVANCED_EDITING' => 'Advanced editing',
    'COLLAPSE_ALL' => 'Collapse all',
    'CREATE_NODE' => 'Create node',
    'DELETE' => 'Delete',
    'EXPAND_ALL' => 'Expand all',
    'NEW_NODE' => 'New node',
    'NEW_NODE_NAME' => 'Enter the new node name',
    'NODE_NAME' => 'Node name',
    'REMOVE_NODE_QUESTION' => 'The nobe will be removed together with the children. Are you sure?',
    'SAVE' => 'Save',
];
