<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ADD_NODE' => 'Añadir nudo',
    'ADVANCED_EDITING' => 'Editar',
    'CLOSE' => 'Cerrar',
    'COLLAPSE_ALL' => 'Contraer todo',
    'CREATE_NODE' => 'Creer nudo',
    'DELETE' => 'Eliminar',
    'EXPAND_ALL' => 'Expandir todo',
    'NEW_NODE' => 'Nudo nuevo',
    'NEW_NODE_NAME' => 'Nombre de nuevo nudo',
    'NODE_NAME' => 'Nombre de nudo',
    'REMOVE_NODE_QUESTION' => 'Nodo será eliminado junto con todos sus nodos secundarios. ¿Seguro?',
    'SAVE' => 'Guardar',
];
