<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ADD_NODE' => 'Добавить узел',
    'ADVANCED_EDITING' => 'Расширенное редактирование',
    'CLOSE' => 'Закрыть',
    'COLLAPSE_ALL' => 'Свернуть все',
    'CREATE_NODE' => 'Создать узел',
    'DELETE' => 'Удалить',
    'EXPAND_ALL' => 'Развернуть все',
    'NEW_NODE' => 'Новый узел',
    'NEW_NODE_NAME' => 'Введите имя нового узла',
    'NODE_NAME' => 'Имя узла',
    'REMOVE_NODE_QUESTION' => 'Узел будет удален вместе со всеми его дочерними узлами. Вы уверены?',
    'SAVE' => 'Сохранить',
];
